-- NOUVEAU: Création de la table Account (Compte utilisateur pour la connexion/sauvegarde)
CREATE TABLE Account (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE, -- Nom d'utilisateur unique
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL, -- Stockage sécurisé du mot de passe
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Création de la table Class (Classe des personnages)
DROP TABLE Class;
CREATE TABLE Class (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    description CLOB,
    base_pv INT NOT NULL,
    base_mana INT NOT NULL,
    strength INT NOT NULL,
    initiative INT NOT NULL,
    max_items INT NOT NULL
);

-- Création de la table Items (Objets disponibles dans le jeu)
DROP TABLE Items;
CREATE TABLE Items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description CLOB,
    item_type VARCHAR(50) NOT NULL -- Ex: 'Arme', 'Armure', 'Potion', etc.
);


-- Création de la table Monster (Monstres rencontrés dans l'histoire)
DROP TABLE Monster;
CREATE TABLE Monster (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    pv INT NOT NULL,
    mana INT,
    initiative INT NOT NULL,
    strength INT NOT NULL,
    attack CLOB,
    xp INT NOT NULL
    -- loot_id supprimé
);

-- Table intermédiaire pour les butins des monstres (Monster - Items)
-- Permet à un monstre de lâcher plusieurs types d'objets, avec une quantité.
DROP TABLE Monster_Loot;
CREATE TABLE Monster_Loot (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monster_id INT,
    item_id INT,
    quantity INT DEFAULT 1 NOT NULL,
    drop_rate DECIMAL(5, 2) DEFAULT 1.0, -- Taux de chance de drop (ex: 0.5 pour 50%)
    FOREIGN KEY (monster_id) REFERENCES Monster(id),
    FOREIGN KEY (item_id) REFERENCES Items(id),
    UNIQUE (monster_id, item_id) -- Un seul type d'objet par monstre dans cette table
);

-- MODIFIÉ: Création de la table Hero (Personnage principal)
-- Les équipements (armor, primary_weapon, etc.) font référence à des Items.
DROP TABLE Hero;
CREATE TABLE Hero (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_id INT, -- Clé étrangère vers Account
    name VARCHAR(50) NOT NULL,
    class_id INT, -- Relation avec Class
    image VARCHAR(255),
    biography CLOB,
    pv INT NOT NULL,
    mana INT NOT NULL,
    strength INT NOT NULL,
    initiative INT NOT NULL,
    
    armor_item_id INT,
    primary_weapon_item_id INT,
    secondary_weapon_item_id INT,
    shield_item_id INT,
    
    spell_list CLOB,
    xp INT NOT NULL,
    current_level INT DEFAULT 1,
    
    FOREIGN KEY (account_id) REFERENCES Account(id), -- Clé étrangère vers Account
    FOREIGN KEY (class_id) REFERENCES Class(id),
    FOREIGN KEY (armor_item_id) REFERENCES Items(id),
    FOREIGN KEY (primary_weapon_item_id) REFERENCES Items(id),
    FOREIGN KEY (secondary_weapon_item_id) REFERENCES Items(id),
    FOREIGN KEY (shield_item_id) REFERENCES Items(id)
);

-- Création de la table Level (Niveaux de progression des classes)
DROP TABLE Level;
CREATE TABLE Level (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INT, -- Relation avec Class
    level INT NOT NULL,
    required_xp INT NOT NULL,
    pv_bonus INT NOT NULL,
    mana_bonus INT NOT NULL,
    strength_bonus INT NOT NULL,
    initiative_bonus INT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES Class(id)
);


-- Création de la table Chapter (Chapitres de l'histoire)
DROP TABLE Chapter;
CREATE TABLE Chapter (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content CLOB NOT NULL,
    image VARCHAR(255)
);

-- Table intermédiaire pour les trésors dans les chapitres (Chapter - Items)
DROP TABLE Chapter_Treasure;
CREATE TABLE Chapter_Treasure (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id INT,
    item_id INT,
    quantity INT DEFAULT 1 NOT NULL,
    FOREIGN KEY (chapter_id) REFERENCES Chapter(id),
    FOREIGN KEY (item_id) REFERENCES Items(id),
    UNIQUE (chapter_id, item_id) -- Un seul type d'objet par chapitre dans cette table
);

-- Création de la table Encounter (Rencontres dans les chapitres)
DROP TABLE Encounter;
CREATE TABLE Encounter (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id INT,
    monster_id INT,
    FOREIGN KEY (chapter_id) REFERENCES Chapter(id),
    FOREIGN KEY (monster_id) REFERENCES Monster(id)
);

-- Table intermédiaire pour l'inventaire des héros (Hero - Items)
DROP TABLE Inventory;
CREATE TABLE Inventory (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_id INT,
    item_id INT,
    quantity INT DEFAULT 1 NOT NULL,
    FOREIGN KEY (hero_id) REFERENCES Hero(id),
    FOREIGN KEY (item_id) REFERENCES Items(id),
    UNIQUE (hero_id, item_id) -- Un seul enregistrement par type d'objet par héros
);

-- Création de la table Links (Liens entre chapitres)
DROP TABLE Links;
CREATE TABLE Links (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id INT,
    next_chapter_id INT,
    description CLOB,
    FOREIGN KEY (chapter_id) REFERENCES Chapter(id),
    FOREIGN KEY (next_chapter_id) REFERENCES Chapter(id)
);

-- Table intermédiaire pour le suivi de progression (Hero - Chapter)
DROP TABLE Hero_Progress;
CREATE TABLE Hero_Progress (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_id INT,
    chapter_id INT,
    status VARCHAR(20) DEFAULT 'Completed', -- Ex: 'Started', 'Completed', 'Failed'
    completion_date DATE, -- Pour marquer quand le chapitre a été terminé
    FOREIGN KEY (hero_id) REFERENCES Hero(id),
    FOREIGN KEY (chapter_id) REFERENCES Chapter(id)
);